### ISSUE TITLE
Email not sent to admin after uploading image with pwg.images.upload

### ISSUE THREAD

**Issue by EddyLB** [plegall/Piwigo-community#24]
I am preparing an image/video upload option for Community users of the iOS app.

After uploading a file with the API method `pwg.images.upload`, an email is not sent to the admin as it is after uploading from the web interface.

Do I miss something or should that be fixed? Something like `contrib_server.photo.submit`?

**Comment by plegall** [comment]
I just pushed the new `community.images.uploadCompleted` API method in d718827467304afaae604ad36f1ba475f020130a

**Comment by plegall** [comment]
@EddyLB ... and I updated your Piwigo dev instance ;-)

**Comment by EddyLB** [comment]
@plegall, the upload option for Community users of the iOS app is operational (v2.1 beta).
A notification is sent each time an image is uploaded. Thank you!

**Comment by EddyLB** [comment]
Would it be possible to add an option so that admins are not notified for some users ?

**Comment by plegall** [comment]
I'm closing this issue, but I'm going to open another one on Piwigo-Mobile repository about the expected use of `community.images.uploadCompleted`.

Concerning the ability to only notify a subset of administrators, that's a good idea, but that's another issue :-)
