### ISSUE TITLE
crash of the plugin following fedora upgrade

### ISSUE THREAD

**Issue by paul-leroy** [plegall/Piwigo-community#34]
Dear all,
First of all, thanks for the good job on this very useful plugin.
I did several upgrades to my server recently and piwigo has crashed due to the community plugin (if I remove it "by hand" and launch my server, I can access my galleries). After several investigations, I think that the problem comes from the file functions_community.inc.php.
It is impossible to launch piwigo if the community plugin is in the plugins directory. The error message being the following. It begins with a warning on the sql request and then, the error:

`Warning:  [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'recursive,
    create_subcategories,
    nb_photos,
    storage
  FROM piwigo_co' at line 6

SELECT
    id,
    type,
    category_id,
    user_album,
    recursive,
    create_subcategories,
    nb_photos,
    storage
  FROM piwigo_community_permissions
  WHERE (type = 'any_visitor')
    OR (type = 'any_registered_user')
    OR (type = 'user' AND user_id = 1)
; in /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php on line 845

Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php:226 Stack trace: #0 /var/www/html/piwigo/plugins/community/include/functions_community.inc.php(102): pwg_db_fetch_assoc(false) #1 /var/www/html/piwigo/plugins/community/main.inc.php(48): community_get_user_permissions('1') #2 /var/www/html/piwigo/include/functions_plugins.inc.php(279): community_init() #3 /var/www/html/piwigo/include/common.inc.php(308): trigger_notify('init') #4 /var/www/html/piwigo/index.php(26): include_once('/var/www/html/p...') #5 {main} thrown in /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php on line 226`

Any idea to solve this issue?

**Comment by paul-leroy** [comment]
The following pull request solve the problem, which comes from mariadb and the fact that recursive is a keyword now:

RECURSIVE_ is a new Keyword in MariaDB 10.2+ - Fix for error

**Comment by Xyaren** [comment]
#33 Fixes this. Please Reopen bug until fixed.

**Comment by plegall** [comment]
Closed by merging PR #33
