### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by buchanan-fh** [plegall/Piwigo-community#45]
After upgrading to PHP 7.2, I get the following error when accessing the admin page of the plugin :

Deprecated: Function create_function() is deprecated in /home/carte-fh/www/galerie_photo/plugins/community/admin.php on line 66

**Comment by 0x4a0x52** [comment]
Replace: 
$tab_codes = array_map(create_function('$a', 'return $a["code"];'), $tabs);

With:
$tab_codes = array_map(
function ($a){
return $a["code"];}, 
$tabs);
