### ISSUE TITLE
Hardcoded file upload

### ISSUE THREAD

**Issue by klackson72** [plegall/Piwigo-community#73]
In the add_photos.tpl on line 204 there is a line that hardcodes uploads to 1gb.  This might be better to read from php settings or have a UI configuration to control it.  as a work around setting it to 100gb has worked for me.  This is really only an issue when using in conjunction with VideoJS and videos are being uploaded.  But in my use case it was a big problem

**Comment by plegall** [comment]
fixed in 9b61e57eb9b7480b6210b130380988015d052849 (will be soon released in Community version 13.a)
