### ISSUE TITLE
 Warnings in Configuration Tab - PHP 8 incompatibility

### ISSUE THREAD

**Issue by francwalter** [plegall/Piwigo-community#77]
Hallo
I just installed Piwigo 13.3.0 local with Apache 2.4 and PHP 8.0
After installing this Plugin  Community I get warnings in the Configuration Tab:

```
C:\Apache24\htdocs\Piwigo\_data\templates_c\p6jhns^5917e50e6ff99ed9cb7da09cf713fa55d706fa71_0.file.admin_config.tpl.php on line 50

Warning: Attempt to read property "value" on null in C:\Apache24\htdocs\Piwigo\_data\templates_c\p6jhns^5917e50e6ff99ed9cb7da09cf713fa55d706fa71_0.file.admin_config.tpl.php on line 50
"> 
```

and when I try to add a permission I get warnings:

```
 Warning: Undefined array key "recursive" in C:\Apache24\htdocs\Piwigo\_data\templates_c\p6jhns^eb3b027ee0951a717a12d7f8a2adbd53abe12cd6_0.file.admin_permissions.tpl.php on line 256

Warning: Attempt to read property "value" on null in C:\Apache24\htdocs\Piwigo\_data\templates_c\p6jhns^eb3b027ee0951a717a12d7f8a2adbd53abe12cd6_0.file.admin_permissions.tpl.php on line 256
> Apply to sub-albums
Warning: Undefined array key "create_subcategories" in C:\Apache24\htdocs\Piwigo\_data\templates_c\p6jhns^eb3b027ee0951a717a12d7f8a2adbd53abe12cd6_0.file.admin_permissions.tpl.php on line 259

Warning: Attempt to read property "value" on null in C:\Apache24\htdocs\Piwigo\_data\templates_c\p6jhns^eb3b027ee0951a717a12d7f8a2adbd53abe12cd6_0.file.admin_permissions.tpl.php on line 259
> ability to create sub-albums
```

When I switch to PHP 7.4 the warnings are gone.
Obviously this plugin is not ready for PHP 8+ but PHP 7+ is deprecated and EOL since weeks now.
It is not the only broken Plugin in Piwigo. I wonder why Piwigo core is updated heavily but many important Plugins, which only make Piwigo worth using, are not, development nearly stopped.

I just used Piwigo after a while again for gathering pictures after a meeting, told the people they could upload their pictures to my gallery.
None of them uploaded any picture, surely because the Plugin didnt work :(
And the forum is broken too, so no way to get it fixed or ask how to fix it.
frank

**Comment by plegall** [comment]
I'm going to fix this, but I'm also going to reply to this:

> I wonder why Piwigo core is updated heavily but many important Plugins,
> which make Piwigo worth using only are not

Because we can't do all at the same time. We're going to fix of help maintainers to fix major plugins to be compatible with PHP 8. The upgrade to PHP 8 has broken many pieces of code. You could also wonder why PHP creators are breaking things this way :-)

**Comment by francwalter** [comment]
OK, thank. And could you fix the forum first?

**Comment by plegall** [comment]
and how is the forum broken? (because of course, it's not broken for many people since we receive some messages)

**Comment by francwalter** [comment]
I tried to reset the password, but never got the email with the password reset link. The forum doesn't send it (broken).

Then I tried to send an email to the forum admin, but never got an answer.

But yesterday I tried again my old password and it works :)

**Comment by francwalter** [comment]
Look, when I try to register in the english forum (the german forum I can login) with username "francwalter" I get the info, that already someone is registered as francwalter. OK then, I try to reset password (the password I used didnt work) with the email I think I used when register (I use always the same for forums) and I get:
![grafik](https://user-images.githubusercontent.com/927269/205596084-863a7607-92d3-4a33-9b0e-a5344cf57176.png)
But do you think that at any time I would get that mail?
Never. I can retry hundreds of times, look in spam and never an email to change my password would come.
So this is broken at least, I think.
Could you fix that?

**Comment by plegall** [comment]
you have my reply by email about the forum issue.

**Comment by ceepeebee213** [comment]
Hi - I know it's been a while but has there been any progress on this? I've come to use Piwigo and get it up and running for a community that I'm looking after (submission-based) and I've come against the same error when using this plugin.

Thanks in advance

**Comment by aptonline** [comment]
Same here, installed the plug-in and receiving the same error when selection the 'Configuration' tab:

```
/config/www/_data/templates_c/p6jhns^89ea1c7dfcba80520cd5ce5c53ef9c82334b8462_0.file.admin_config.tpl.php on line 50

Warning: Attempt to read property "value" on null in /config/www/_data/templates_c/p6jhns^89ea1c7dfcba80520cd5ce5c53ef9c82334b8462_0.file.admin_config.tpl.php on line 50
"> 
```

**Comment by MrFranke** [comment]
Same problem
Downgrade Piwigo fix this issue for me

**Comment by francwalter** [comment]
Downgrade Piwigo to which version?
I thought this is PHP 8 related!?

**Comment by MrFranke** [comment]
@francwalter version 11.5.0, 
yes, this version include old PHP version

**Comment by francwalter** [comment]
This i not understand!
Piwigo is only **running** under PHP but does not contain the PHP.

PHP 7.4 is now old and deprecated and should not be used anymore on any server in the internet, exposed to attacks with unfixed security issues.
On my server I switched to 8.0, in November 22.
8.0 is EOL as well end of this year, then I will upgrade to 8.1 or even 8.2 or 8.3.
I don't want to take that risk to be hacked, this is not a sugar licking, to fix such things and you loose reputation as well (I run a mail server, reputation there  is crucial).
Piwigo without that community plugin is just another gallery.
For me the feature that other user could upload their pictures is the very only feature I really need, **would** need at the moment.
But I understand that this takes time and it is done by unpaid enthusiasts, so I won't complain ;)

**Comment by aptonline** [comment]
Any update on this issues?

**Comment by Bulgus** [comment]
Same issue.
`PHP : 8.0.28
Piwigo : 13.7.0`

**Comment by francwalter** [comment]
It is something in that smarty template:

`plugins/community/admin_config.tpl`

There is in line 23 that 

```
...
<form method="post" action="{$F_ACTION}">
...
```

where the `$F_ACTION->value` is empty (null) and so the form action is broken (and with it the form).
That could have worked in PHP 7, to pass empty values to the template, I guess, but not anymore in 8.
When I remove that Smarty Var in action=" then the error disappears. So now I have in line 23 only:

`<form method="post" action="">`

But there are more errors, on the Upload permission tab, when I try to add a permission, there are errors in this template:

`plugins/community/admin_permissions.tpl`

In line 199 and 201:

...
<label><input type="checkbox" name="recursive" {if $recursive}checked="checked"{/if}> {'Apply to sub-albums'|@translate}</label>
<label><input type="checkbox" name="create_subcategories" {if $create_subcategories}checked="checked"{/if}> {'ability to create sub-albums'|@translate}</label>
...

also here the PHP errors from it:

```
 Warning: Undefined array key "recursive" in /.../piwigo/_data/templates_c/p6jhns^0f1ddb6710e71a347e282ec638ca65aa8e04158d_0.file.admin_permissions.tpl.php on line 256

Warning: Attempt to read property "value" on null in /.../piwigo/_data/templates_c/p6jhns^0f1ddb6710e71a347e282ec638ca65aa8e04158d_0.file.admin_permissions.tpl.php on line 256

Warning: Undefined array key "create_subcategories" in /.../piwigo/_data/templates_c/p6jhns^0f1ddb6710e71a347e282ec638ca65aa8e04158d_0.file.admin_permissions.tpl.php on line 259

Warning: Attempt to read property "value" on null in /.../galerie/piwigo/_data/templates_c/p6jhns^0f1ddb6710e71a347e282ec638ca65aa8e04158d_0.file.admin_permissions.tpl.php on line 259

```

I deleted also here the parts which are throwing errors, so now I have in line 199 and 201 of 
`plugins/community/admin_permissions.tpl`
this:
`<label><input type="checkbox" name="recursive" </label>`
and
`<label><input type="checkbox" name="create_subcategories" </label>`
and the PHP Warnings (errors) are gone.

But I dont know if that deleting didnt break something and have not the time to test that.

**Comment by DickyC915** [comment]
500 Internal Server Error when i click setting with Piwigo 15.5.0 and PHP 8.1.32
and PHP 8.1 will EOL soon
could we upgrade the PHP?
