### ISSUE TITLE
Config -> Save Settings button does nothing

### ISSUE THREAD

**Issue by tuxroller** [plegall/Piwigo-community#78]
Admin panel -> Community plugin configuration -> Configuration tab. Save Settings button opens "Open with..." browser dialog instead save plugin configuration.

Piwigo v 13.7.0
Community plugin v 12.c
Checked browsers - Firefox 113, Chromium 113
PHP 8.0
Client OS - Kubuntu 22.04

P.S. seems like it's related to #77

**Comment by tuxroller** [comment]
Really! It's related to #77. When I try workaround from this comment https://github.com/plegall/Piwigo-community/issues/77#issuecomment-1544109698
```
plugins/community/admin_config.tpl
```
```
<form method="post" action="">
```
"Open with..." dialog gone out and config succesfully saved!
Don't know if something else become broken with this fix.

**Comment by plegall** [comment]
#77 fixed, will be in next Community version
