### ISSUE TITLE
switch from Flash to HTML5

### ISSUE THREAD

**Issue by plegall** [plegall/Piwigo-community#9]
for the upload form

**Comment by sakanaou** [comment]
Dear @plegall, do you have any timeline for this? Apart from myself I think that many others are eagerly waiting for this feature. Especially as Piwigo itself switched to HTML5 already. Thanks in advance!

**Comment by plegall** [comment]
I "would like" it to be done before 2017. It is an important improvement. Flash is obsolete and Community is a major feature for Piwigo. We need to give high priority to this issue!

**Comment by lubbergerc** [comment]
Any update on the timeline? As you said, Flash is obsolete, so Community shouldn't rely on it any more. But it is still the only way to upload multiple photos at once.

**Comment by habakuk007** [comment]
Would love to see this implemented. I cannot use Flash and the switch to the html upload form doesn't work  (The url is https://invalid.com/index/add_photos&upload_mode=html and it leads to the main page of the gallery).

**Comment by tjw1184** [comment]
I'm also having issues with flash and the html upload and would very much like for the html5 upload to get implemented.  @plegall do you have any updates on the timeline for this feature to get implemented?

**Comment by habakuk007** [comment]
Any news on this?

**Comment by plegall** [comment]
I'm working on it :-)
![community-upload-html5](https://cloud.githubusercontent.com/assets/9326959/26829226/f787f8d0-4ac4-11e7-8b6c-6c331dae6f80.png)

**Comment by shadow974** [comment]
any news here?
